### ISSUE TITLE
AUTO BUG REPORT: incompatible types, c_long instance instead of c_ushort instance

### ISSUE THREAD

**Issue by CALOAReportSender** [vigoux/CALOA#70]
Windows-7-6.1.7601-SP1
CPython-3.6.5

```python
Traceback (most recent call last):

  File "application.py", line 470, in routine_data_sender
    intTime=float(self.config_dict[self.ROUT_INT_TIME].get())

  File "C:\Program Files (x86)\CALOA\spectro.py", line 682, in prepareAll
    self.prepareMeasure(device, intTime, triggered, nrAverages)

  File "C:\Program Files (x86)\CALOA\spectro.py", line 577, in prepareMeasure
    Meas.m_StartPixel = ctypes.c_int(0)

TypeError: incompatible types, c_long instance instead of c_ushort instance


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\pixel\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)

  File "C:\Users\pixel\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 746, in callit
    func(*args)

  File "application.py", line 475, in routine_data_sender
    self.avh.prepareAll()

  File "C:\Program Files (x86)\CALOA\spectro.py", line 682, in prepareAll
    self.prepareMeasure(device, intTime, triggered, nrAverages)

  File "C:\Program Files (x86)\CALOA\spectro.py", line 577, in prepareMeasure
    Meas.m_StartPixel = ctypes.c_int(0)

TypeError: incompatible types, c_long instance instead of c_ushort instance

```

**Comment by vigoux** [comment]
Fixed in v0.17.7.3
