### ISSUE TITLE
AUTO BUG REPORT: incompatible types, c_byte instance instead of c_ubyte instance

### ISSUE THREAD

**Issue by CALOAReportSender** [vigoux/CALOA#74]
Windows-7-6.1.7601-SP1
CPython-3.6.5

```python
Traceback (most recent call last):

  File "application.py", line 470, in routine_data_sender
    intTime=float(self.config_dict[self.ROUT_INT_TIME].get())

  File "C:\Program Files (x86)\CALOA\spectro.py", line 693, in prepareAll
    self.prepareMeasure(device, intTime, triggered, nrAverages)

  File "C:\Program Files (x86)\CALOA\spectro.py", line 585, in prepareMeasure
    tp_Trigger.m_Source = ctypes.c_byte(0)

TypeError: incompatible types, c_byte instance instead of c_ubyte instance


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\pixel\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)

  File "C:\Users\pixel\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 746, in callit
    func(*args)

  File "application.py", line 475, in routine_data_sender
    self.avh.prepareAll()

  File "C:\Program Files (x86)\CALOA\spectro.py", line 693, in prepareAll
    self.prepareMeasure(device, intTime, triggered, nrAverages)

  File "C:\Program Files (x86)\CALOA\spectro.py", line 585, in prepareMeasure
    tp_Trigger.m_Source = ctypes.c_byte(0)

TypeError: incompatible types, c_byte instance instead of c_ubyte instance

```

**Comment by vigoux** [comment]
Issue solved in release [v0.17.7.11](https://github.com/Mambu38/CALOA/releases/tag/v0.17.7.11)
