### ISSUE TITLE
AUTO BUG REPORT: prepareAll() got an unexpected keyword argument 'triggered'

### ISSUE THREAD

**Issue by CALOAReportSender** [vigoux/CALOA#75]
Windows-7-6.1.7601-SP1
CPython-3.6.5

```python
Traceback (most recent call last):

  File "C:\Users\pixel\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)

  File "application.py", line 917, in experiment
    nrAverages=p_N_c)

TypeError: prepareAll() got an unexpected keyword argument 'triggered'

```

**Comment by vigoux** [comment]
Fixed in release [v0.17.7.13](https://github.com/Mambu38/CALOA/releases/tag/v0.17.7.13)
