### ISSUE TITLE
AUTO BUG REPORT: [WinError 183] Impossible de créer un fichier déjà existant: 'C:/Program Files (x86)/CALOA/data\\saves6_7_15_33'

### ISSUE THREAD

**Issue by CALOAReportSender** [vigoux/CALOA#82]
Windows-7-6.1.7601-SP1
CPython-3.6.5

```python
Traceback (most recent call last):

  File "C:\Users\pixel\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)

  File "application.py", line 1064, in experiment
    self.treatSpectras(raw_timestamp)

  File "application.py", line 1117, in treatSpectras
    os.mkdir(save_dir)

FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'C:/Program Files (x86)/CALOA/data\\saves6_7_15_33'

```

**Comment by vigoux** [comment]
False positive
